### ISSUE TITLE
Format numbers according to user locale

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#106]
This goes for all numbers in throughout the app that have **expected values larger than 999 or include decimals**. Use two decimals by default. 

Use JS `Intl.NumberFormat`

**Comment by yussdev** [comment]
We use two decimals already: 
![image](https://github.com/GeneralMagicio/pw-frontend/assets/51474231/ce0e7936-fc5d-4f07-afbd-3583243a91da)

**Comment by kristoferlund** [comment]
@yussdev Great, but not the international number formatting based on users locale, so that `202221.00` becomes `202,221.00` in US and `202 221,00` in Sweden.

**Comment by yussdev** [comment]
as we don't have a Switch for changing the locale if we use that API the numbers will be formatted based on the browser locale, Is that OK?

**Comment by kristoferlund** [comment]
@yussdev Yes, browser default locale is great.
