### ISSUE TITLE
Include pairwise in impactCategory when creating list

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#109]
https://bafybeid5x2d6xijihphdkvt7mvk74ds2pn5o6eu7mdvlplrylozozxogra.ipfs.w3s.link/metadata.json

**Comment by mmahdigh** [comment]
Should we just put "Pairwise" there or also the planet name? Because we share our planet names with Agora's categories? (Except for the "Individual" planet, though) @kristoferlund

**Comment by kristoferlund** [comment]
@mmahdigh This is what I received from Stephan:

> Hey guys, just confirming that you'll be adding `"impactCategory": ["Pairwise"]` field to your list attestations ?

**Comment by kristoferlund** [comment]
@mosaeedi New reply from Stephan: 

> Technically multiple categories are supported but it's more of a UX question. Actually seems like a great idea, considering you're going to have a lot of lists. Just keep in mind that we'll only be allowing filtering for a single category. Meaning that if user selects Pairwise, they will see all Pairwise lists, and if they select "End user experience & adoption", they will see all "End user experience & adoption" including pairwise and non pairwise.

That means we can and should do more than one category.

**Also, `impactCategory` should be uppercase.**

**Comment by mosaeedi** [comment]
I'm not sure I get what we need to do!?
