### ISSUE TITLE
Make sure all back links lead "back"

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#110]
Use `History.back()` to ensure any back links takes user back to where they came from

**Comment by yussdev** [comment]
Is there any case that isn't working? 
@kristoferlund

**Comment by kristoferlund** [comment]
@yussdev not sure, once Mahdi has merged the new flow we can check. Just wanted this issue as a reminder to test and verify.

**Comment by kristoferlund** [comment]
@yussdev 

This back link does not lead to the correct destination:
* Clicking on `Ranking` from `/galaxy/x` takes you to main ranking page. `Back` then leads back to `/galaxy`.

Also, other click issues:
* Dragging planets on galaxy and planet view leads to a click when you stop dragging. This should not be the case.
