### ISSUE TITLE
More landing page UI fixes

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#121]
* Last section have some gfx glitches:
  - Format numbers US style `100,234.99`
  - Replace squares with locks
* Graphics still uses wrong terms. Begin ranking should be used, not Awaiting direction.

<img width="862" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/119decf2-43ad-4ceb-a829-3b22c15c4080">
<img width="639" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/b745e8ad-bce9-4154-b709-a8f367ef1634">

**Comment by yussdev** [comment]
@kristoferlund @mosaeedi  So these fixes should be applied in design first then in front

**Comment by kristoferlund** [comment]
I belive @mosaeedi said he had new design assets ready?

**Comment by yussdev** [comment]
The numbers are not updated in the votes section ( US format ) and the lock icon has the styling issues 
@kristoferlund @mosaeedi

**Comment by yussdev** [comment]
Oh no:))) @mosaeedi We need the whole svg If you update  it in Figma It will be useful 
And also the numbers should  be formatted as mentioned here:

> @yussdev @mosaeedi
> 
> First look, will look more in 20 mins
> 
> * Apply `git merge staging` and resolve any confilicts
> * Last section have some gfx glitches:
>   
>   * Format numbers US style `100,234.99`
>   * Replace squares with locks
> 
> <img alt="image" width="862" src="https://user-images.githubusercontent.com/9698363/279989280-119decf2-43ad-4ceb-a829-3b22c15c4080.png">

**Comment by kristoferlund** [comment]
@mosaeedi This issue have been open for 6 days now, please help us sort this out. If that locka icon dont work with export, find a new icon. Or.. bring it into Photoshop and paste some icons. Or if it is a SVG, open it up in Illustrator and fix manually there.

**Comment by kristoferlund** [comment]
@mosaeedi  Ok, thanks. We are not using any individual icons but the whole "Voted projects" block from Figma as one big SVG. It's ok, I'll export it as a PNG instead. 

But is really the intention that it should be cut off on the left side and the greyed out edit field to the right compared to the others?

<img width="836" alt="Screenshot 2023-11-08 at 16 18 00" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/ec2dff45-898f-4bc7-9b1f-c2d09dbedd66">

**Comment by mosaeedi** [comment]
Ohhh, got it.
I didn't know that you needed it as a photo.
So sorry, I'll fix that ASAP.

**Comment by mosaeedi** [comment]
<img width="914" alt="Screenshot 2023-11-09 at 10 51 08 AM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/a249a7dd-3788-46ab-96a0-37d6b1bd9d9a">

@kristoferlund Is this precisely what you need?
If that's okay, I'll share the SVG export here.

**Comment by mosaeedi** [comment]
Should I also copy the percentage and the op allocation as well?

**Comment by yussdev** [comment]
@mosaeedi Actually we don't use the exported files , we copy them on Figma which is more easier for us 
Figma links are so helpfull to grap the assets

**Comment by mosaeedi** [comment]
<img width="198" alt="Screenshot 2023-11-09 at 10 58 26 AM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/01f17037-c849-4fea-a26d-7484c5bde22f">

I'm also suggesting using the PNG export rather than SVG, because it's a big file with many details, the SVG file will be heavier.

**Comment by mosaeedi** [comment]
Here is the link to the updated Figma file.

[Figma link](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2744-21526&mode=design&t=7gpw9pVgaFXf61Uw-4)

**Comment by yussdev** [comment]
Thanks

**Comment by yussdev** [comment]
This is how it's gonna look like: 
<img width="1232" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/51474231/ecd1af73-21ae-4d8d-9398-496ca800f9ae">

**Comment by mosaeedi** [comment]
I think it's okay!
@kristoferlund WDYT?
