### ISSUE TITLE
Make the text wrap for category names instead of adding "..."

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#128]
<img width="319" alt="Screenshot 2023-11-03 at 12 03 10 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/b017a2e9-8e8d-438d-9e0d-7f9fa2e8783e">

Right now its cutting off the category name, the whole name should be shown in the box and it should just go to 2 lines IMO

**Comment by kristoferlund** [comment]
How would you like to handle this @mosaeedi ?

**Comment by mosaeedi** [comment]
<img width="314" alt="Screenshot 2023-11-08 at 1 22 53 AM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/cdf1de11-a838-4e44-9d1c-af2cea061431">

We can let the name go to the second line, but still, we need to set a limit to avoid getting to the third line!

**Comment by kristoferlund** [comment]
@mosaeedi We don't have that long category names. I will allow two lines of text and we are good.
