### ISSUE TITLE
High Priority - quick issue - when the user has a small window size, we should have a pop up telling them to use a bigger screen

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#130]
<img width="490" alt="Screenshot 2023-11-03 at 12 42 49 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/7619320b-e284-40e1-b3fb-c43a197c485c">

It looks really bad, i don't think we should optimize for mobile anytime soon.... but we should pop up something that says something like:

Pairwise was optimized for larger screen sizes

Or something like that

**Comment by GriffGreen** [comment]
Chat GPT said these options:

- "Best viewed on a desktop"
- "This site is optimized for desktop use"
- "For full functionality, please use a desktop browser"
- "Mobile version not available"
- "Optimized for desktop viewing"
- "Switch to a desktop for the best experience"
- "Desktop or laptop recommended for this site"
- "Experience full features on a desktop browser"
- "Mobile-friendly version coming soon"
- "Use a desktop to enhance your experience"
- "Not currently optimized for mobile devices"
- "For optimal performance, please access via a desktop computer"
- "This website is intended for desktop resolutions"
- "Please visit this site on a desktop for best functionality"

**Comment by mosaeedi** [comment]
It's covered in issue #47 
I also think it's a valid and important issue we must address.

cc: @kristoferlund

**Comment by kristoferlund** [comment]
@mosaeedi If you make a simple design of that screen, we will add it.
