### ISSUE TITLE
Extra info needed on details (project)

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pw-frontend#133]
In the detail we need to include impact metrics and budget received ( if we can not we could link to supermodular/agora project page, where you click details and goes automatically there)

**Comment by kristoferlund** [comment]
In the application data, we have three lists. Add these lists to the scrolling section of the dialog. Simple formatting, below is example for TypeChain (applicantAddress: 0xb41c548387CF11dC6553CD134C76754D5820EBe1):

## Contribution Links
* [GITHUB_REPO](https://github.com/dethcrypto/TypeChain) - TypeChain's main repo.
* [OTHER](https://github.com/search?q=org%3Aethereum-optimism+typechain&type=code) - TypeChain usage in Optimism org
...

## Impact Metrics
* [TC Weekly downloads (~60% growth YoY)](https://www.npmjs.com/package/typechain): 339138
...

## Funding Sources
* RETROPGF_2, 4493867 OP, RPGF grant
...

**Comment by kristoferlund** [comment]
@yussdev You can fetch the metadata info you need from this link:

![image](https://github.com/GeneralMagicio/pw-frontend/assets/9698363/e1de3b95-1c27-4b16-a7b9-3321ac4c0a55)

**Comment by yussdev** [comment]
Fixed! @kristoferlund
