### ISSUE TITLE
Edit in the rank page works funny

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pw-frontend#134]
The manual edit when modifying a percentage is giving invalid value  (in this example any value below 24.03 should be valid and take away from other moons and if i want it even higher i should put more budget into the planet)

![image](https://github.com/GeneralMagicio/pw-frontend/assets/74430951/c2c9ddef-174e-4bf1-bd88-e1fc84b8011c)

**Comment by kristoferlund** [comment]
We will remove percentages completely. Closing this issue.
