### ISSUE TITLE
Minnor issue, help module

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pw-frontend#137]
[ ] old image in the help popo up (1 and 2)
![image](https://github.com/GeneralMagicio/pw-frontend/assets/74430951/356a5e00-9804-425c-b9e1-ae577d44bd1e)

[ ] need a better copy: suggestion:
![image](https://github.com/GeneralMagicio/pw-frontend/assets/74430951/c8a82325-c5e0-4914-a32b-86b5f8725335)

Expertise-Driven Curation

Delve into the topics you know best and craft lists that truly reflect your insights. With the flexibility to make manual adjustments, you can tailor each list to meet your exact criteria. Remember, once you switch to manual editing, the path to comparison-based adjustments will close. Make your expertise count and finalize your lists with confidence.

[ ] copy changes:
![image](https://github.com/GeneralMagicio/pw-frontend/assets/74430951/5ce12695-a5d8-4359-bfed-9668b0163d64)

Navigate to the 'Ranking' section now! View all the allocations you've made to each area and get ready to submit your lists!

**Comment by kristoferlund** [comment]
We have new copy based on your suggestions in the Miro board, closing this one for now. Please make new issue if edits are still needed.
