### ISSUE TITLE
Replace GM favicon with Pairwise favicon

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#148]

**Comment by yussdev** [comment]
@mosaeedi Would you please provide Pairwise favicon?

**Comment by mosaeedi** [comment]
@rodricastillo9013 worked on the Logo, but I can't find it now to produce the favicon.
Let me find it first.

**Comment by kristoferlund** [comment]
@mosaeedi it is in the Figma, in the sandbox

**Comment by mosaeedi** [comment]
[Pairwise_favicon.zip](https://github.com/GeneralMagicio/pw-frontend/files/13297292/Pairwise_favicon.zip)
