### ISSUE TITLE
New copy needed for landing page initial paragraphs

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#150]
<img width="1139" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/13576f86-8385-4943-b70c-687776dce098">

Tasks:

- [ ] Reconsider "Impact = Profit"
- [ ] Shorter and more concise version of "Empowering Badgeholders"

**Comment by kristoferlund** [comment]
@Zeptimus @krisis

**Comment by krisjpi** [comment]
Possible alternatives for "Impact = Profit"
- Making OP Allocations Easy!
- RetroPGF Allocations, Simplified
- Ensure that impact = OP in RetroPGF
- Allocation Tools for Badgeholders (?boring?)

**Comment by krisjpi** [comment]
First swing at a revision on the **Empowering Badgeholders** section

Pairwise is a platform for quickly curating project lists for RetroPGF 3! Immerse yourself in an experience built to empower you in rewarding impact. Contribute to allocating funding in the Optimism ecosystem and have fun doing it!

**Comment by Zeptimus** [comment]
oh no, i missed that I hope we keep Impact=profit and empowering badgeholder what about: Enhance Your Role?
