### ISSUE TITLE
Decimal error when creating list attestations

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#154]
List attestation gets 10x the OP value per project.

Pairwise UI:

<img width="1148" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/f4c4be45-3b8d-4631-9e25-6e3a66c98c9c">

RetroPGF voting:

<img width="702" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/76c6f136-6e30-4acd-857e-57d83310d6e4">

**Comment by mmahdigh** [comment]
Actually, The OP in the attestation is correct. We have to multiply the percentages by 30 million in the app. We're multiplying them by three million currently.
