### ISSUE TITLE
Authentication prompt appears too soon (Ubuntu Opera, Ubuntu Brave)

### ISSUE THREAD

**Issue by krisjpi** [GeneralMagicio/pw-frontend#159]
Staging site loads into authentication too soon if you haven't connected a wallet yet. Very easy to lose the connect wallet button and need a refresh. When navigating to the main pairwise intro page for the first time, the "Connect Wallet" button appeared only for a second before prompting the Authentication, which is never picked up by the wallet. Metamask shows "no accounts connected" and connection can't be initiated from there.

Was able to refresh and hit the Connect Wallet button before it disappeared, and then was able to progress through the flow normally.

likely low priority as it is a bit of an edge case for OS and browsers.

**Comment by kristoferlund** [comment]
This is fixed
