### ISSUE TITLE
Cannot change initial allocations - "Invalid Value"

### ISSUE THREAD

**Issue by krisjpi** [GeneralMagicio/pw-frontend#161]
I am unable to edit the initial allocations even before starting ranking any projects. Going straight to the Rankings page after the intro slides and editing one of the numbers manually gives me an "Invalid Value" error in place of the "Save" button.

This limits (IMO) the expression of allocation preference and changes the default. Also if this is expected behaviour, some edits are needed in the intro slides (we say you can edit initial allocations in the intro)

This is on Chrome on Windows 11, though I experienced it in my Ubuntu tests as well.

I think this is a high priority fix

**Comment by kristoferlund** [comment]
This is solved
