### ISSUE TITLE
Auto expand categories sub-categories when linking to rankings page

### ISSUE THREAD

**Issue by krisjpi** [GeneralMagicio/pw-frontend#162]
Problem: It's easy to get lost when jumping from the end of ranking a category and going to the main ranking page to edit.

Example: I finish ranking "DeFi, Decentralized Finance" in OP Stack, and want to edit the project allocations. I jump to the main rankings screen, and am faced with top level categories: End User Experience & Adoption, Developer Ecosystem, OP Stack... but it's not clear which category I just came from.

Is it possible to have rankings expanded to the category the user is coming from? 
So, I came from ranking DeFi, Decentralized Finance", so when I get to the ranking page, have "OP Stack">"DeFi, Decentralized Finance" expanded?

**Comment by kristoferlund** [comment]
Great, I have been thinking to do this one.

Links to the ranking page should include information about category or subcategory to expand on page load. Examples:

### `/ranking?c=3`

Auto expands "Developer Ecosystem" on load

### `/ranking?c=17`

Auto expands  "Developer Ecosystem / Developer Tools - Smart Contracts"
