### ISSUE TITLE
Consider "Back" button change on Rankings screen

### ISSUE THREAD

**Issue by krisjpi** [GeneralMagicio/pw-frontend#165]
I can understand using the back button to go back to the category I left.  However, if a user goes to edit their allocations, they are likely to follow that by submitting a list, or moving on to another category. There doesn't seem to be an easy way back from the ranking screen, though you can get to a specific category from there.

Under the three dot menu we have Details, Continue ranking, (Begin Ranking) ,and Create list. These options hit all the important user paths, but the Continue Ranking and Back buttons share a path, from different areas of the page. 

Consider changing the path of the Back button to the Planets section rather than the last category. Alternatively, consider adding another button to go back to the planets page.

Video meant to simulate user trying to get to planets using current paths, and also encountering some unexpected behaviours ("rank other projects" took me to the Rankings page and that page's back button took me to the planets page).

https://github.com/GeneralMagicio/pw-frontend/assets/41163644/bc60b0d7-394a-4008-a341-2ace48e1b88a

**Comment by kristoferlund** [comment]
Good suggestion! 

To summarize:
- If user is coming from the pairwise voting screen to the ranking page, back button leads to galaxy page.
