### ISSUE TITLE
Footer of landing page needs more love | missing links to socials

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pw-frontend#171]
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/53ccf813-e868-449c-98e6-529278c36ecf)

Let's remove them if we don't have socials.

**Comment by kristoferlund** [comment]
Pairwise don't have any socials, right?

Let's keep these three:
- Github, link to pairwise frontend repo
- Twitter: General Magic Twitter
- Discord: General Magic Discord

**Comment by kristoferlund** [comment]
@yussdev you should find links here: https://www.generalmagic.io/
