### ISSUE TITLE
I edited, saved and click on back button, Im visiting a blank page now. 

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pw-frontend#172]
I edited, saved, and clicked on the back button, I am visiting a blank page now. 

![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/0846f34d-6f75-4a17-8581-5a5f8601e3d5)

**Comment by MoeNick** [comment]
Tested on:
https://pairwise-frontend-git-feature-new-editing-flow-general-magic.vercel.app/poll/6

**Comment by MoeNick** [comment]
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/787018d1-cc24-471b-bc3e-ce2caffa4aaa)

The back button should go to galaxy or planet view, right now it starts voting again.

**Comment by MoeNick** [comment]
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/b3d64599-f41b-4da5-984d-f4543ac11d87)

Actually, it happens when the user leads to the landing page from the edit dialog. 
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/f30020af-ec07-454c-bdc1-37e1716ad01e)

**Comment by kristoferlund** [comment]
This is solved
