### ISSUE TITLE
I changed my chain, DApp did not respond, I can go ahead but could not attest.

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pw-frontend#173]
I changed my chain, DApp did not respond, I can go ahead but could not attest.

**Comment by MoeNick** [comment]
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/b874820b-3e68-466b-89ca-14553544604c)

**Comment by kristoferlund** [comment]
We should log out user when chain is changed. And show a "wrong network" button. 

I'll fix this one.

**Comment by kristoferlund** [comment]
Done. 

https://github.com/GeneralMagicio/pw-frontend/pull/179
