### ISSUE TITLE
Low Priority - When you click the planet that should also open up the voting page

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#174]
I want to click the planet to go to the voting screen... but nothing happens

<img width="491" alt="Screenshot 2023-11-08 at 10 36 23 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/01105f9b-6098-463e-b2c1-c8516ae968c2">

**Comment by kristoferlund** [comment]
This is solved
