### ISSUE TITLE
Edit ranking

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#176]
<img width="1433" alt="Screenshot 2023-11-09 at 09 29 51" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/c3dd713e-16d5-4c76-989d-3e3b1623c359">

### Use lock instead of stop sign
Even though we internally differentiate between something being locked or disabled, that distinction don't matter to the end user. The result is still that row cannot be edited. I propose we **keep using the lock symbol for disabled rows** as well, not the stop sign.

### Help the user understand what they can edit
Currently the locked rows look almost more prominent than the active ones. **Make sure locked rows look toned down / disabled and that the active ones stand out**.

### Use popovers more effectively. 
- Remove the "Please enter a valid value.." tooltip, it does not add much value
- Add popover on disabled rows: "Complete more rankings in this category to unlock."
- Add popover on locked rows: "Row is locked, click the lock icon to unlock"

### Signal "Invalid value" more clearly.
- A red warning icon next to edit field?
- Popover with helpful message: "The entered value is to high/low/something, max/min allowed value for this row is XXX"
- No "Invalid value" on save button, instead just make button disabled.

### Warn user about the consequences of making manual edits. 
- Every time user clicks "Edit" button, show popup warning user "After making manual adjustments to a category, you can't do any more pairwise rankings for that category"

### Inform user no more pairwise ranking can be done for a category
- When manual edits have been done for a category, no more pairwise rankings can be done. Inform the user about this in the context menu. Instead of "Continue ranking →" we should have a disabled text there: "No more ranking can be done"

### Help the user differentiate between the levels
- We have three levels of rows on this page. Different the colour/opacity slightly for the different level to help guide the user.

**Comment by mosaeedi** [comment]
**1. Use lock instead of stop sign**
I'm agree that we use just lock and unlocked button instead of having the stop sign.
I've made some changes to the locked and unlocked state to fix the ux issue. 

<img width="676" alt="Screenshot 2023-11-09 at 2 00 29 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/0b87c3ab-50f0-4667-9347-362808f93c4b">

[**Link to Figma**](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2744-21526&mode=design&t=mUIFWNO0WEzUtjLQ-4)

**Comment by mosaeedi** [comment]
**3. Use popovers more effectively**

<img width="841" alt="Screenshot 2023-11-09 at 2 12 36 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/822c0bd2-17e2-42cb-a68d-55e602ff29b5">


[**Link to Figma** ](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2753-23312&mode=design&t=mUIFWNO0WEzUtjLQ-4)

**Comment by mosaeedi** [comment]
4. Signal "Invalid value" more clearly.

<img width="497" alt="Screenshot 2023-11-09 at 2 50 29 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/2db7aaf3-ce92-4ccf-91a3-59150df06b7c">

[**Link to Figma**](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2753-24044&mode=design&t=rpxE92GhDqCt0d8v-4)

**Comment by mosaeedi** [comment]
**5. Warn user about the consequences of making manual edits.**


<img width="820" alt="Screenshot 2023-11-09 at 3 03 47 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/4301ea04-087b-4936-b099-2d7c6fe47429">

[**Link to Figma**](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2756-25770&mode=design&t=rpxE92GhDqCt0d8v-4)

**Comment by mosaeedi** [comment]
**6. Inform user no more pairwise ranking can be done for a category**

<img width="355" alt="Screenshot 2023-11-09 at 3 07 04 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/790ba572-cb07-4e42-b0b4-c2b713086a79">

**Comment by mosaeedi** [comment]
**7. Help the user differentiate between the levels**

I didn't understand the last one!

**Comment by kristoferlund** [comment]
> **7. Help the user differentiate between the levels**

@mosaeedi the colors of these rows perhaps could be slightly different to more clearly communicate the three levels to the user.

<img width="751" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/3c8970eb-3807-4030-94ac-134a850ed47b">

**Comment by mosaeedi** [comment]
Oh, I got it.

I think it's better to reduce the opacity rather than change colors.

**Background opacity on levels:**
Level 1: 100%
Level 2: 70%
Level 3: 50%

[Link to Figma](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2546-15314&mode=design&t=rpxE92GhDqCt0d8v-4)

**Comment by GriffGreen** [comment]
<img width="463" alt="Screenshot 2023-11-09 at 3 31 18 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/3638d260-f705-422e-a4ad-26d3f36ac759">

We need to figure out a better word than rankings... it doesn't sound right 

For now i would say:

"Make more assessments in this category to unlock."
