### ISSUE TITLE
Add close button to attestation confirmation dialog

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pw-frontend#181]
Im here and I don;t have a clue how can I close the modal or get back to that ranking again? 

![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/65e11fc0-75d5-49e3-8492-3ee47efaa8d9)

**Comment by kristoferlund** [comment]
X in the corner is enough.

**Comment by kristoferlund** [comment]
Done
