### ISSUE TITLE
UX improvement | disabling 'cancel' while the user interacts with MM attesting a list

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pw-frontend#184]
When the user interacts with MM, and approves the transaction, "not yet" button is still clickable. so I can create a list without being able to see my lists somewhere. 

![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/44f2d8c8-5490-4ef4-8ca8-809b23f28687)

**Comment by kristoferlund** [comment]
Both buttons should be disabled while creating list. Also, try to give as much context on the progress as possible. Can we get better progress updates than just `Loading...`?
