### ISSUE TITLE
Medium Priority, quick fix, make the red "%" sign larger and have it be after the number

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#188]
<img width="573" alt="Screenshot 2023-11-09 at 5 54 46 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/c4a286f2-cf17-4ffb-92ce-372125e8c8a5">

And make it larger so it seems like the same font size as the numbers

**Comment by kristoferlund** [comment]
Done
