### ISSUE TITLE
low priority - text change throughout the app - "Complete more Rankings" sounds awkward

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#193]
<img width="723" alt="Screenshot 2023-11-10 at 8 34 04 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/5dd9c866-4573-48d6-b50d-b304fbf775ba">

I changed it in one place on the figma... but it seems to be in others, i'm not sure...

Either way, I'm pretty sure in any context we can:

ctrl-f and replace 

"Complete more rankings"

with

"Rank more projects"

Everywhere

**Comment by kristoferlund** [comment]
Fixed
