### ISSUE TITLE
Replace all occurences: Supermodular -> West

### ISSUE THREAD

**Issue by krisjpi** [GeneralMagicio/pw-frontend#194]
In the [Optimism docs](https://community.optimism.io/docs/governance/retropgf-3/#voting), voting platforms are labeled Agora and West.

Where we have Supermodular, replace with West.

![Pairwise_SubmitList](https://github.com/GeneralMagicio/pw-frontend/assets/41163644/0ef6555a-bae7-449f-aba7-53d5730e71bf)

**Comment by krisjpi** [comment]
The issue exists in the Create List card as well.

Wording changes suggested on this card:
"After creating this list, you can no longer do pairwise rankings in [Category]"
or
"After creating this list, you cannot do any more pairwise rankings in [Category]"

And

"Lists that you create here can be used for RetroPGF voting in Agora and West"

![Pairwise_CreateList](https://github.com/GeneralMagicio/pw-frontend/assets/41163644/514bd58a-fec1-46bb-b91c-cb93660d2386)

**Comment by kristoferlund** [comment]
Fixed
