### ISSUE TITLE
Edit fields in Rankings for sub-categories looks un-editable?

### ISSUE THREAD

**Issue by krisjpi** [GeneralMagicio/pw-frontend#195]
Maybe this is a personal preference, but the fields to edit OP allocations in subcategories in the Rankings section look like they are locked by default, even though they aren't. Can we keep the unlocked fields white and when locked grey?

Especially if users edited the top level categories early on, the locked field has a similar color to the unlocked fields in the sub-categories.

![Pairwise_Rankings](https://github.com/GeneralMagicio/pw-frontend/assets/41163644/3db2193c-7d14-4a25-b3a5-a5a3fa7be110)
![Pairwise_RankingsLocked](https://github.com/GeneralMagicio/pw-frontend/assets/41163644/86c9e557-caf9-4676-adc9-903ec8a903eb)

**Comment by krisjpi** [comment]
![Pairwise_RankingsEditedLocked](https://github.com/GeneralMagicio/pw-frontend/assets/41163644/22543003-c64d-46f8-89ba-6e7969b3998e)

**Comment by kristoferlund** [comment]
This should be more clear now.
