### ISSUE TITLE
Bug in "Edit manually" flow 

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pw-frontend#198]
When there is a item in "inprogress" status when I tap on "Edit manually" the status changed to "Ranked " , Is this accepted result ?
@MoeNick @mmahdigh 
https://github.com/GeneralMagicio/pw-frontend/assets/111529185/27b2d9c3-1a94-4f97-92a8-21a92449e48c

**Comment by mmahdigh** [comment]
Yes. However, if you test it now, we have a warning modal that essentially warns the user once they decide to edit a collection manually, they can no longer do pairwise votes in that collection. (i.e., the collection would be 'ranked")
