### ISSUE TITLE
High Priority - Quick Fix - Change "Abstain" to "Neither" and have a tool tip that explains how it works

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#200]
<img width="1531" alt="Screenshot 2023-11-12 at 4 35 10 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/3dc1ad57-265a-4327-8d87-180a1e119392">

Abstain should be "Neither"

And when someone scrolls over it the tool tip reads:

"Choose neither if it is too close to call or you don't want to give OP to either project."

 (I would suggest that we make it so if they scroll over the box ANYWHERE this tool tip pops up... but i understand if you want to put a big ? circle or something)

**Comment by kristoferlund** [comment]
We have room to add explainer text below "Abstain". Show on hover only though.
