### ISSUE TITLE
Low Priority - small formatting - Update the details formatting and add a place holder for when they have no funding sources

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#204]
2 issues here:
<img width="897" alt="Screenshot 2023-11-12 at 7 39 17 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/be0c53f1-8ca8-4022-a89a-62689f4d2878">

- [ ] Even tho they didn't include any Funding Sources, I think having the header there and saying "None" is better than not having anything there.... this should also be the case if they have no contributions or impact metrics, etc
- [ ] The OTHER is hyperlinked... but really, the OTHER shouldnt be hyperlinked, it should be the other text

**Comment by kristoferlund** [comment]
done
