### ISSUE TITLE
Reduce number of clicks it takes to edit a category

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#205]
Kind of related to #202, there is a design choice to make only one place where you can edit manually... I disagree with this choice after doing user testing... people can't figure out how to edit.

When clicking this edit button on this page:
<img width="899" alt="Screenshot 2023-11-12 at 8 12 36 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/d4b51a9e-5949-4257-97a2-961d26b04b14">

you go to this state:
<img width="1150" alt="Screenshot 2023-11-12 at 8 15 22 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/8b73c58a-a6a1-4d4d-bb4f-08dc67d6ff8a">

But the state we want them to be in is:

<img width="1175" alt="Screenshot 2023-11-12 at 8 18 09 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/967d70da-d672-495a-ba5c-8f612af4f230">

Honestly I don't see a great argument for EVER showing that first state, we just need to some how prompt them to save whenever they make edits.... 

Also... I think these options to edit or continue
<img width="376" alt="Screenshot 2023-11-12 at 4 38 45 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/edc335c6-e574-4bd5-964c-a874450431f1">

should be in this 3 dot drop down too:
<img width="540" alt="Screenshot 2023-11-12 at 5 35 01 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/e9e6010e-f693-4995-99fe-faa34ee4fe8d">

AND!

I think this needs more of a Warning: Like is should use big caution signs and stuff like that, cause no one reads text
<img width="507" alt="Screenshot 2023-11-12 at 6 17 20 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/14945613/560b80ec-c75d-4453-9e8e-62f31703c5c9">

**Comment by kristoferlund** [comment]
@GriffGreen 

Straight forward solution to this one would be to show a warning directly when clicking on the `Edit` button in the "Well done" dialog. 

![image](https://github.com/GeneralMagicio/pw-frontend/assets/9698363/83d93d18-719f-4d14-99a5-46132aaffbe3)

When user clicks `Edit manually` they are taken to the ranking edit page with category ready to be edited.

**Comment by kristoferlund** [comment]
Summary:
- When clicking on edit in pairwise ranking modal
  1. Show warning modal
  2. Finish category
  3. Open ranking page in edit mode for right category (add a new qs parameter, maybe `&edit=true`.
- Make warning modal more of a **Warning** modal!
  - Replace header with: Warning

**Comment by krisjpi** [comment]
Came to check here instead of starting a new issue - I think the fix suggested above will work well. It seems like the change in flow of a category to "Finished" makes this a little weird.

Giving a warning and an option to manually finish ranking to be able to edit should deal with this.

Attached a short clip finishing ranking (but not creating the list) and wanting to edit.

https://github.com/GeneralMagicio/pw-frontend/assets/41163644/00a345b2-28e7-41f0-8622-7a08cd7b74ce
