### ISSUE TITLE
Create list issue

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pw-frontend#208]
Is it accepted that the user could see "Create list" option and completeing flow after that the user has completed this flow 
@MoeNick @mmahdigh 
<img width="1440" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/111529185/8fac4d60-8af6-4695-bfa6-845e24e83d9c">

**Comment by mmahdigh** [comment]
Yes. We first revoke the previous list and then create a new one. A better copy may be warranted?

**Comment by kristoferlund** [comment]
Change copy in context menu when list have already been created: `Recreate list`

**Comment by kristoferlund** [comment]
Fixed

**Comment by maryjaf** [comment]
Could you change the button in this modal like as the list? that after creating list the text button be changed to "Recreate list" 
@kristoferlund @mmahdigh 
<img width="944" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/111529185/37e31373-3136-4b75-883c-8c3d7200f4cd">

**Comment by kristoferlund** [comment]
@maryjaf 👍 #219
