### ISSUE TITLE
New UX: Help Modals

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pw-frontend#22]
As a user after I answered the 2 main questions, I would like to see an explanation modal ONLY one time, to show me how it works:

1st Step:
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/3999d2a4-6d7b-4878-819e-840c19727d58)

2nd:
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/c261779d-4106-4a65-9c5a-0cf7d3b40533)

3rd:
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/5ae976b7-9872-4661-a397-d0eee971e3af)

In last step, Got it button can close the modal.

Design:
https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=1938-19452&mode=design&t=eYOzYZ427Yua1XaG-4

NOTE: Clicking on HELP icon in the footer will let the user see these modals again 
![image](https://github.com/GeneralMagicio/pw-frontend/assets/80677512/35598725-b82f-4f2c-98bf-5cab5ebdf76f)

**Comment by Zeptimus** [comment]
How is the best way for me to work text editions?
