### ISSUE TITLE
UPDATE THESE NAMES! HIGH PRIORITY!

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#237]
We have the first name ----> Change it to the name after the arrow

- [ ] B<>rder/ess ----> borderless

- [x] Bored Town ----> Bored Town NFT art community

- [x] Optimism Prime ----> c2ba

- [x] OP News by ETH Daily ----> ETH Daily (OP News)

- [x] LandTorn ----> LandTorn - Lorak

- [x] Cap ----> Namespace

- [x] Blockchain +Indexer ----> Onboard en Perú Optimistas e Indexer

- [x] Cryptofox ----> Optiland Quests

- [x] Optimism Grants Council ----> Optimism Grants Council Season 4

- [x] Unlock Protocol ----> Patrick Workman (Unlock Protocol)

- [x] Protofire ----> Protofire Blockchain Learning Path

**Comment by kristoferlund** [comment]
B<>rder/ess ----> borderless are two different things. All other changes verified.
