### ISSUE TITLE
ADD these 3 projects to Pairwise!

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pw-frontend#239]
- [x] Add "Edge & Node / The Graph" to "Explorers, Security & Node Deployment Tools" in "Developer Ecosystem" https://vote.optimism.io/retropgf/3/application/0x8526b3343ae97a1859ff98d7f7d414ba2f47735d62a84b94f5aef514b5260aa6

- [x] Add "Mirror Curator DAO" to "DAOs, ReFi, and DAO Tooling" in "Collective Governance" https://vote.optimism.io/retropgf/3/application/0x6565449e46eba1283b32efd00d98c22aa9c43ccfb2edc7c79747e311a04284c9

- [x] Add "sorryvrerror" to "NFTs" in "Individuals" https://vote.optimism.io/retropgf/3/application/0x16975e7a89132161310d5fb63766352915c0311044748fa7ee80ea507812edde

**Comment by kristoferlund** [comment]
Done
