### ISSUE TITLE
Well done modal

### ISSUE THREAD

**Issue by mosaeedi** [GeneralMagicio/pw-frontend#75]
<img width="1058" alt="Screenshot 2023-10-18 at 2 36 11 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/1f0c162d-ee23-4dad-a594-72d08002b4b7">

This modal should be positioned in the middle.

Also, as I've mentioned in issue #48, the body font weight should be reduced to **400**

**Comment by kristoferlund** [comment]
@mosaeedi I have not looked at any issues older than #99 (when I arrived in the project). I don't know if it is now prioritised to work on these older issues. @MoeNick ?
